In [1]:
import pandas as pd
import xlwings as xw
import os

os.chdir("P:\자동데이타생성")
bk1 = xw.Book('03W225_AI44B5O.xlsx')

In [2]:
sh1 = bk1.sheets(1)
sh1.name

'취합'

In [3]:
sh2 = bk1.sheets(2)
sh2.name

'125-12'

In [4]:
sh3 = bk1.sheets(3)
sh3.name

'125-14'

In [5]:
sh4 = bk1.sheets(4)
sh4.name

'125-16'

In [6]:
sh5 = bk1.sheets(5)
sh5.name

'125-18'

In [7]:
df1_des = bk1.sheets(1).range('B3:M13').options(pd.DataFrame, index=False, header=False).value

#df1 = bk1.sheets(1).used_range.options(pd.DataFrame, index=False, header=False).value
#sht.range('A1').options(pd.DataFrame, index=False, header=False, expand='table').value
#df1 = df1.astype('float')
df1_des.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       11 non-null     object
 1   1       11 non-null     object
 2   2       11 non-null     object
 3   3       11 non-null     object
 4   4       11 non-null     object
 5   5       11 non-null     object
 6   6       11 non-null     object
 7   7       11 non-null     object
 8   8       11 non-null     object
 9   9       11 non-null     object
 10  10      11 non-null     object
 11  11      11 non-null     object
dtypes: object(12)
memory usage: 1.2+ KB


In [8]:
df1_des

0            1            2            3            4   \
0         820.0        821.0        822.0        823.0        824.0   
1      220621.0     220621.0     220621.0     220621.0     220622.0   
2   6/23(15:00)  6/23(15:00)  6/23(15:00)  6/23(15:00)  6/23(15:00)   
3      145253.0     145253.0     145253.0     145253.0     145600.0   
4        B3 1-2       B3 1-2       B3 1-2       B3 1-2       B3 2-1   
5        03W225       03W225       03W225       03W225       03W225   
6       AI44B5O      AI44B5O      AI44B5O      AI44B5O      AI44B5O   
7          40.0         40.0         40.0         40.0         40.0   
8         125.0        125.0        125.0        125.0        135.0   
9          12.0         14.0         16.0         18.0         12.0   
10        200.0        200.0        200.0        200.0        100.0   

             5            6            7            8            9   \
0         825.0        826.0        827.0        828.0        829.0   
1      220622.0     220622.0     220622.0     220623.0     220623.0   
2   6/23(15:00)  6/23(15:00)  6/23(15:00)  6/23(15:00)  6/23(15:00)   
3      145600.0     145600.0     145600.0     145723.0     145723.0   
4        B3 2-1       B3 2-1       B3 2-1       B3 2-2       B3 2-2   
5        03W225       03W225       03W225       03W225       03W225   
6       AI44B5O      AI44B5O      AI44B5O      AI44B5O      AI44B5O   
7          40.0         40.0         40.0         40.0         40.0   
8         135.0        135.0        135.0        145.0        145.0   
9          14.0         16.0         18.0         12.0         14.0   
10        100.0        100.0        100.0        100.0        100.0   

             10           11  
0         830.0        831.0  
1      220623.0     220623.0  
2   6/23(15:00)  6/23(15:00)  
3      145723.0     145723.0  
4        B3 2-2       B3 2-2  
5        03W225       03W225  
6       AI44B5O      AI44B5O  
7          40.0         40.0  
8         145.0        145.0  
9          16.0         18.0  
10        100.0        100.0

In [9]:
temp = df1_des.iloc[8].to_list()
volt = df1_des.iloc[9].to_list()
quantity = df1_des.iloc[7].to_list()
time = df1_des.iloc[10].to_list()

column = [str(int(temp[i])) + '-' + str(float(volt[i])) for i in range(len(temp))]
# [x+y for x,y in zip(list1, list2)]
print(temp, volt, quantity, time, column)

# df1_des.loc[12] = column
# df1_des

[125.0, 125.0, 125.0, 125.0, 135.0, 135.0, 135.0, 135.0, 145.0, 145.0, 145.0, 145.0] [12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0] [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] [200.0, 200.0, 200.0, 200.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0] ['125-12.0', '125-14.0', '125-16.0', '125-18.0', '135-12.0', '135-14.0', '135-16.0', '135-18.0', '145-12.0', '145-14.0', '145-16.0', '145-18.0']


In [10]:
print(type(column), type(column[0]))

<class 'list'> <class 'str'>


In [11]:
df1_data = bk1.sheets(1).range('B14').options(pd.DataFrame, index=False, header=False, expand='table').value
# ※header에 cloumn 사용 시 type error

#df1 = bk1.sheets(1).used_range.options(pd.DataFrame, index=False, header=False).value
#sht.range('A1').options(pd.DataFrame, index=False, header=False, expand='table').value
#df1 = df1.astype('float')
df1_data = df1_data.round(1) #used_range 미사용 시 문제 없음

df1_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       40 non-null     float64
 1   1       40 non-null     float64
 2   2       40 non-null     float64
 3   3       40 non-null     float64
 4   4       40 non-null     float64
 5   5       40 non-null     float64
 6   6       40 non-null     float64
 7   7       40 non-null     float64
 8   8       40 non-null     float64
 9   9       40 non-null     float64
 10  10      40 non-null     float64
 11  11      40 non-null     float64
dtypes: float64(12)
memory usage: 3.9 KB


In [12]:
df1_data

0     1     2     3     4     5     6     7     8     9    10   11
0   136.8  77.9  49.4  31.9  46.3  32.3  17.3   9.9  16.3  13.0  6.6  4.7
1   119.4  72.3  36.9  35.6  41.3  24.5   2.2   8.4  18.5  12.1  7.6  4.4
2   128.6  66.3  44.5  42.5  40.6  31.0  18.3   9.8  19.6  10.3  6.5  2.2
3   121.8  88.9  47.2  26.2  47.7  29.7  19.1   3.2  17.7   6.2  7.7  4.1
4   117.1  82.4  35.1  33.9  47.9  12.0  17.9  13.2  17.4   6.8  6.5  4.4
5   153.3  94.0  52.4   8.7  34.7  25.0  14.7   9.8  17.4  11.1  5.7  5.5
6   112.9  70.5  51.1  33.1  42.9  29.0  14.5  11.1  18.3   7.8  8.6  2.3
7   165.9  81.7  51.6   8.9  47.4  21.7  15.7   9.5  17.9  11.1  6.0  5.0
8   145.7  80.6  45.8  29.3  48.4  25.5  15.3  12.6  13.3  13.0  7.8  4.1
9   130.2  80.4  55.8  36.5  36.7  30.3  17.9  10.2  16.3  10.0  7.1  4.8
10  144.5  81.4  34.0  27.1  24.2  25.9  13.9  11.9  11.0  10.8  8.5  5.9
11  128.4  88.4  46.4  13.0  41.0  27.5  18.1  11.2  17.7  10.5  7.2  5.3
12   71.1  71.2  52.8  42.4  48.4  27.4  10.8  11.8  12.8  10.6  5.7  4.5
13  116.8  83.6  29.4  35.9  50.7  19.7  16.5  10.3  17.0  10.0  7.8  3.5
14  133.2  84.9  50.1  26.8  47.5  26.6  18.0   9.8  19.2  10.3  6.4  5.0
15  131.9  59.8  44.1  36.0  47.9  28.1  18.3  11.8  15.6   9.5  7.8  1.3
16  137.8  80.9  48.0  33.7  48.3  27.0  10.5   9.7  13.2  11.4  6.8  5.4
17  142.9  80.1  34.4  26.3  37.2  23.8  16.9  11.9  18.4   9.1  5.7  4.8
18  146.8  71.3  50.0  28.3  38.7  29.9  13.4  12.6  11.7  10.7  5.9  5.1
19  125.7  79.7  34.2  36.8  49.9  25.1  14.9   7.9  19.1  12.7  1.5  4.6
20  140.4  93.8  29.6  30.1  40.8  32.6  19.1  12.0  18.2  12.5  7.4  4.1
21  123.3  64.6  52.2  32.7  43.3  29.6  18.2   9.8  20.1  11.8  7.0  4.6
22  118.6  84.1  58.0  23.7  43.6  26.0  18.0  12.0   5.2   9.6  6.2  3.0
23  142.0  81.5  50.5  35.0  12.6  27.6  17.0  11.0  21.1  10.5  6.8  4.9
24   92.2  71.0  37.1  34.2  46.0  19.0  19.1   9.7  15.8   9.4  6.5  5.5
25  121.1  82.7  45.2  29.0  46.5  27.4  18.5  11.4  18.5  11.9  7.5  4.6
26  116.4  86.2  58.8   8.3  50.6  28.2  14.2  11.3  13.9   8.5  3.9  5.5
27   15.7  80.6  18.1  27.6  39.3  12.4  14.8  11.1  20.0  11.5  7.3  1.7
28  143.2  85.6  55.3  27.4  41.5  27.3  14.7  13.0  14.6  11.9  7.1  2.6
29  130.3  38.8  59.4  29.5  54.5  12.3  18.4  11.8  19.1  11.4  6.5  4.5
30  136.1  79.3  44.4  30.5  42.0  31.4  16.2   7.0  19.6  10.8  6.4  2.8
31  132.7  73.1  40.4  30.4  51.0  22.8  18.4  11.6  17.0  11.5  6.2  3.6
32   95.6  83.6  43.1  29.7  23.6  29.7  15.3   9.5  16.3  11.0  7.5  3.9
33  142.3  76.5  55.8  14.5  48.3  16.9  14.3  11.2  11.6   8.4  6.5  3.2
34   96.2  45.3  25.0  25.0  46.1  34.2  15.0  12.3  17.5   4.8  5.9  0.8
35  154.9  79.1  46.8  11.4  49.1  32.3  19.1  11.1  17.7  10.7  5.9  2.5
36  148.3  93.4  52.3  32.2  52.2  15.0  14.4  11.9  19.6  10.1  6.2  3.8
37  147.9  67.6  47.0  22.7  38.3  33.5  16.7  14.2  19.9   9.4  7.0  4.8
38  137.9  94.0  54.2  17.1  45.9  28.5  12.9   7.0   6.3   9.7  4.8  4.2
39   76.8  87.2  54.0  37.9  40.6  26.5  15.5  12.8  20.8  12.3  6.3  5.2

In [14]:
show_data=df1_data
show_data.columns = column

max_quan = 40
new_index = range(1,max_quan+1)
show_data.index = new_index

show_data

125-12.0  125-14.0  125-16.0  125-18.0  135-12.0  135-14.0  135-16.0  \
1      136.8      77.9      49.4      31.9      46.3      32.3      17.3   
2      119.4      72.3      36.9      35.6      41.3      24.5       2.2   
3      128.6      66.3      44.5      42.5      40.6      31.0      18.3   
4      121.8      88.9      47.2      26.2      47.7      29.7      19.1   
5      117.1      82.4      35.1      33.9      47.9      12.0      17.9   
6      153.3      94.0      52.4       8.7      34.7      25.0      14.7   
7      112.9      70.5      51.1      33.1      42.9      29.0      14.5   
8      165.9      81.7      51.6       8.9      47.4      21.7      15.7   
9      145.7      80.6      45.8      29.3      48.4      25.5      15.3   
10     130.2      80.4      55.8      36.5      36.7      30.3      17.9   
11     144.5      81.4      34.0      27.1      24.2      25.9      13.9   
12     128.4      88.4      46.4      13.0      41.0      27.5      18.1   
13      71.1      71.2      52.8      42.4      48.4      27.4      10.8   
14     116.8      83.6      29.4      35.9      50.7      19.7      16.5   
15     133.2      84.9      50.1      26.8      47.5      26.6      18.0   
16     131.9      59.8      44.1      36.0      47.9      28.1      18.3   
17     137.8      80.9      48.0      33.7      48.3      27.0      10.5   
18     142.9      80.1      34.4      26.3      37.2      23.8      16.9   
19     146.8      71.3      50.0      28.3      38.7      29.9      13.4   
20     125.7      79.7      34.2      36.8      49.9      25.1      14.9   
21     140.4      93.8      29.6      30.1      40.8      32.6      19.1   
22     123.3      64.6      52.2      32.7      43.3      29.6      18.2   
23     118.6      84.1      58.0      23.7      43.6      26.0      18.0   
24     142.0      81.5      50.5      35.0      12.6      27.6      17.0   
25      92.2      71.0      37.1      34.2      46.0      19.0      19.1   
26     121.1      82.7      45.2      29.0      46.5      27.4      18.5   
27     116.4      86.2      58.8       8.3      50.6      28.2      14.2   
28      15.7      80.6      18.1      27.6      39.3      12.4      14.8   
29     143.2      85.6      55.3      27.4      41.5      27.3      14.7   
30     130.3      38.8      59.4      29.5      54.5      12.3      18.4   
31     136.1      79.3      44.4      30.5      42.0      31.4      16.2   
32     132.7      73.1      40.4      30.4      51.0      22.8      18.4   
33      95.6      83.6      43.1      29.7      23.6      29.7      15.3   
34     142.3      76.5      55.8      14.5      48.3      16.9      14.3   
35      96.2      45.3      25.0      25.0      46.1      34.2      15.0   
36     154.9      79.1      46.8      11.4      49.1      32.3      19.1   
37     148.3      93.4      52.3      32.2      52.2      15.0      14.4   
38     147.9      67.6      47.0      22.7      38.3      33.5      16.7   
39     137.9      94.0      54.2      17.1      45.9      28.5      12.9   
40      76.8      87.2      54.0      37.9      40.6      26.5      15.5   

    135-18.0  145-12.0  145-14.0  145-16.0  145-18.0  
1        9.9      16.3      13.0       6.6       4.7  
2        8.4      18.5      12.1       7.6       4.4  
3        9.8      19.6      10.3       6.5       2.2  
4        3.2      17.7       6.2       7.7       4.1  
5       13.2      17.4       6.8       6.5       4.4  
6        9.8      17.4      11.1       5.7       5.5  
7       11.1      18.3       7.8       8.6       2.3  
8        9.5      17.9      11.1       6.0       5.0  
9       12.6      13.3      13.0       7.8       4.1  
10      10.2      16.3      10.0       7.1       4.8  
11      11.9      11.0      10.8       8.5       5.9  
12      11.2      17.7      10.5       7.2       5.3  
13      11.8      12.8      10.6       5.7       4.5  
14      10.3      17.0      10.0       7.8       3.5  
15       9.8      19.2      10.3       6.4       5.0  
16     

In [15]:
# 시험온도, 시험전압 테이블 추출
test_temp = list(set(temp))
#print(temp, test_temp)
test_temp = [int(x) for x in test_temp if pd.isnull(x) == False]
test_temp.sort()
#print(test_temp)
test_temp = [str(x) for x in test_temp if pd.isnull(x) == False]
print(test_temp)

test_volt = list(set(volt))
test_volt = [float(x) for x in test_volt if pd.isnull(x) == False]
test_volt.sort()
test_volt = [str(x) for x in test_volt if pd.isnull(x) == False]
print(test_volt)

# 테스트 수량 추출
test_quantity = list(set(quantity))
#print(temp, test_temp)
test_quantity = [int(x) for x in test_quantity if pd.isnull(x) == False]
#test_quantity.sort()

max_quantity = max(test_quantity)
print(max_quantity)

test_time = time

print(test_time)

['125', '135', '145']
['12.0', '14.0', '16.0', '18.0']
40
[200.0, 200.0, 200.0, 200.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]


In [16]:
testcond = pd.DataFrame(columns = test_volt, index = test_temp)
print(testcond)

    12.0 14.0 16.0 18.0
125  NaN  NaN  NaN  NaN
135  NaN  NaN  NaN  NaN
145  NaN  NaN  NaN  NaN


In [17]:
testcond = testcond.fillna('V')
print(testcond)             
#bike_data.loc[bike_data.Gender.isnull(), 'Gender'] = 'U'

    12.0 14.0 16.0 18.0
125    V    V    V    V
135    V    V    V    V
145    V    V    V    V


In [18]:
print(type(test_temp), type(test_temp[0]))

<class 'list'> <class 'str'>


In [19]:
import numpy as np

max_data = max_quantity
i = len(test_temp)
j = len(test_volt)
k = max_data

data_array= np.zeros((i, j, k))

count=0
for x in range(len(test_temp)):
    for y in range(len(test_volt)):
        data_array[x][y] = df1_data.loc[0:39, count]
        data_array[x][y] = sorted(data_array[x][y])
        count += 1   
        
#for x in range(len(column)):
#    df1_data[x] = df1_data[x].apply(lambda r: f'{np.round(r, decimals=1):.1f}')

#df1_data
        
print(data_array, type(data_array), type(data_array[0][0][0]))

KeyError: 0

In [20]:
print(list(range(len(test_temp))))

[0, 1, 2]


In [21]:
from itertools import combinations, product

temp_comb = list(combinations(list(range(len(test_temp))), 2))
volt_comb = list(combinations(list(range(len(test_volt))), 2))

unit_comb = list(product(temp_comb,volt_comb))

print(temp_comb)
print(volt_comb)
print(unit_comb)

[(0, 1), (0, 2), (1, 2)]
[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
[((0, 1), (0, 1)), ((0, 1), (0, 2)), ((0, 1), (0, 3)), ((0, 1), (1, 2)), ((0, 1), (1, 3)), ((0, 1), (2, 3)), ((0, 2), (0, 1)), ((0, 2), (0, 2)), ((0, 2), (0, 3)), ((0, 2), (1, 2)), ((0, 2), (1, 3)), ((0, 2), (2, 3)), ((1, 2), (0, 1)), ((1, 2), (0, 2)), ((1, 2), (0, 3)), ((1, 2), (1, 2)), ((1, 2), (1, 3)), ((1, 2), (2, 3))]


In [22]:
for i in range(len(temp_comb)):
    print(test_temp[temp_comb[i][0]], test_temp[temp_comb[i][1]])

print('\n')
    
for i in range(len(volt_comb)):
    print(test_volt[volt_comb[i][0]], test_volt[volt_comb[i][1]])

print('\n')
print('temp_subset    /    volt_subset')

print(len(unit_comb), unit_comb[0][0], unit_comb[0][1])

125 135
125 145
135 145


12.0 14.0
12.0 16.0
12.0 18.0
14.0 16.0
14.0 18.0
16.0 18.0


temp_subset    /    volt_subset
18 (0, 1) (0, 1)


In [23]:
for i in range(len(unit_comb)):
    print(unit_comb[i][0], unit_comb[i][1]) 

print('\n')
print('temp_unitset    /    volt_unitset')

for i in range(len(unit_comb)):
    #for j in range(0,1):
        print(test_temp[unit_comb[i][0][0]], '-', test_temp[unit_comb[i][0][1]], ' / ', test_volt[unit_comb[i][1][0]], '-', test_volt[unit_comb[i][1][1]])

(0, 1) (0, 1)
(0, 1) (0, 2)
(0, 1) (0, 3)
(0, 1) (1, 2)
(0, 1) (1, 3)
(0, 1) (2, 3)
(0, 2) (0, 1)
(0, 2) (0, 2)
(0, 2) (0, 3)
(0, 2) (1, 2)
(0, 2) (1, 3)
(0, 2) (2, 3)
(1, 2) (0, 1)
(1, 2) (0, 2)
(1, 2) (0, 3)
(1, 2) (1, 2)
(1, 2) (1, 3)
(1, 2) (2, 3)


temp_unitset    /    volt_unitset
125 - 135  /  12.0 - 14.0
125 - 135  /  12.0 - 16.0
125 - 135  /  12.0 - 18.0
125 - 135  /  14.0 - 16.0
125 - 135  /  14.0 - 18.0
125 - 135  /  16.0 - 18.0
125 - 145  /  12.0 - 14.0
125 - 145  /  12.0 - 16.0
125 - 145  /  12.0 - 18.0
125 - 145  /  14.0 - 16.0
125 - 145  /  14.0 - 18.0
125 - 145  /  16.0 - 18.0
135 - 145  /  12.0 - 14.0
135 - 145  /  12.0 - 16.0
135 - 145  /  12.0 - 18.0
135 - 145  /  14.0 - 16.0
135 - 145  /  14.0 - 18.0
135 - 145  /  16.0 - 18.0


In [24]:
comb_3_cond = np.zeros((72, 3, 40))
ret = np.zeros((18, 4, 3, 2))

#print(comb_3_cond, '\n\n', ret)

In [25]:
for i in range(0,18):
    tot_set = list(product(unit_comb[i][0], unit_comb[i][1]))
    final_comb = list(combinations(tot_set, 3))
    print(final_comb)
    ret[i] = np.array(final_comb)
    
#print(type(final_comb), final_comb)
# 변수명 수정 : last_last → final_comb
print(type(ret), type(ret[0]), type(ret[0][0]), type(ret[0][0][0]), type(ret[0][0][0][0]), '\n', ret)

[((0, 0), (0, 1), (1, 0)), ((0, 0), (0, 1), (1, 1)), ((0, 0), (1, 0), (1, 1)), ((0, 1), (1, 0), (1, 1))]
[((0, 0), (0, 2), (1, 0)), ((0, 0), (0, 2), (1, 2)), ((0, 0), (1, 0), (1, 2)), ((0, 2), (1, 0), (1, 2))]
[((0, 0), (0, 3), (1, 0)), ((0, 0), (0, 3), (1, 3)), ((0, 0), (1, 0), (1, 3)), ((0, 3), (1, 0), (1, 3))]
[((0, 1), (0, 2), (1, 1)), ((0, 1), (0, 2), (1, 2)), ((0, 1), (1, 1), (1, 2)), ((0, 2), (1, 1), (1, 2))]
[((0, 1), (0, 3), (1, 1)), ((0, 1), (0, 3), (1, 3)), ((0, 1), (1, 1), (1, 3)), ((0, 3), (1, 1), (1, 3))]
[((0, 2), (0, 3), (1, 2)), ((0, 2), (0, 3), (1, 3)), ((0, 2), (1, 2), (1, 3)), ((0, 3), (1, 2), (1, 3))]
[((0, 0), (0, 1), (2, 0)), ((0, 0), (0, 1), (2, 1)), ((0, 0), (2, 0), (2, 1)), ((0, 1), (2, 0), (2, 1))]
[((0, 0), (0, 2), (2, 0)), ((0, 0), (0, 2), (2, 2)), ((0, 0), (2, 0), (2, 2)), ((0, 2), (2, 0), (2, 2))]
[((0, 0), (0, 3), (2, 0)), ((0, 0), (0, 3), (2, 3)), ((0, 0), (2, 0), (2, 3)), ((0, 3), (2, 0), (2, 3))]
[((0, 1), (0, 2), (2, 1)), ((0, 1), (0, 2), (2, 2)), ((

In [26]:
print(type(final_comb))
#com_3_cond = d
for i in range(0,2):
    print(final_comb[0][i])
    
    
    
for i in range(0,18):
    print(test_temp[unit_comb[i][0][0]], '-', test_temp[unit_comb[i][0][1]], ' / ', test_volt[unit_comb[i][1][0]], '-', test_volt[unit_comb[i][1][1]])

<class 'list'>
(1, 2)
(1, 3)
125 - 135  /  12.0 - 14.0
125 - 135  /  12.0 - 16.0
125 - 135  /  12.0 - 18.0
125 - 135  /  14.0 - 16.0
125 - 135  /  14.0 - 18.0
125 - 135  /  16.0 - 18.0
125 - 145  /  12.0 - 14.0
125 - 145  /  12.0 - 16.0
125 - 145  /  12.0 - 18.0
125 - 145  /  14.0 - 16.0
125 - 145  /  14.0 - 18.0
125 - 145  /  16.0 - 18.0
135 - 145  /  12.0 - 14.0
135 - 145  /  12.0 - 16.0
135 - 145  /  12.0 - 18.0
135 - 145  /  14.0 - 16.0
135 - 145  /  14.0 - 18.0
135 - 145  /  16.0 - 18.0


In [27]:
output_array = np.zeros((18, 4, 3, 40))

for i in range(0,18):
    for j in range(0,4):
        for k in range(0,3):
            #comb_data = data_array[final_comb[i][j][k][0]][final_comb[i][j][k][1]]
            output_array[i][j][k] = data_array[int(ret[i][j][k][0])][int(ret[i][j][k][1])]
            #print(comb_data)

print(output_array)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


In [28]:
# temp = df1_des.iloc[8].to_list()
# volt = df1_des.iloc[9].to_list()
# quantity = df1_des.iloc[7].to_list()
# time = df1_des.iloc[10].to_list()

# column = [str(int(temp[i])) + '-' + str(float(volt[i])) for i in range(len(temp))]
# # [x+y for x,y in zip(list1, list2)]
# print(temp, volt, quantity, time, column)


# output
# [125.0, 125.0, 125.0, 125.0, 135.0, 135.0, 135.0, 135.0, 145.0, 145.0, 145.0, 145.0]
# [12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0]
# [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] 
# [200.0, 200.0, 200.0, 200.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0] 
# ['125-12.0', '125-14.0', '125-16.0', '125-18.0', '135-12.0', '135-14.0', '135-16.0', '135-18.0', '145-12.0', '145-14.0', '145-16.0', '145-18.0']


# title_array2 = np.zeros((72, 3, 2))

title_array=[] 
title_array2=[]

print(type(title_array2), title_array2)

for i in range(0,18):
    for j in range(0,4):
        for k in range(0,3):
            title_array.append(test_temp[int(ret[i][j][k][0])] + '-' + test_volt[int(ret[i][j][k][1])]) 
 
# Array로 수정
for i in range(0, 216, 3):
    title_array2.append(title_array[i] + '/' + title_array[i+1] + '/' + title_array[i+2]) 
    
# for i in range(0, 18*4*3, 3):
#     title_array2.append(title_array[i] + '/' + title_array[i+1] + '/' + title_array[i+2]) 
    
print(title_array2)    

# for i in range(0, 18*4*3):
#     print(title_array[i])

<class 'list'> []
['125-12.0/125-14.0/135-12.0', '125-12.0/125-14.0/135-14.0', '125-12.0/135-12.0/135-14.0', '125-14.0/135-12.0/135-14.0', '125-12.0/125-16.0/135-12.0', '125-12.0/125-16.0/135-16.0', '125-12.0/135-12.0/135-16.0', '125-16.0/135-12.0/135-16.0', '125-12.0/125-18.0/135-12.0', '125-12.0/125-18.0/135-18.0', '125-12.0/135-12.0/135-18.0', '125-18.0/135-12.0/135-18.0', '125-14.0/125-16.0/135-14.0', '125-14.0/125-16.0/135-16.0', '125-14.0/135-14.0/135-16.0', '125-16.0/135-14.0/135-16.0', '125-14.0/125-18.0/135-14.0', '125-14.0/125-18.0/135-18.0', '125-14.0/135-14.0/135-18.0', '125-18.0/135-14.0/135-18.0', '125-16.0/125-18.0/135-16.0', '125-16.0/125-18.0/135-18.0', '125-16.0/135-16.0/135-18.0', '125-18.0/135-16.0/135-18.0', '125-12.0/125-14.0/145-12.0', '125-12.0/125-14.0/145-14.0', '125-12.0/145-12.0/145-14.0', '125-14.0/145-12.0/145-14.0', '125-12.0/125-16.0/145-12.0', '125-12.0/125-16.0/145-16.0', '125-12.0/145-12.0/145-16.0', '125-16.0/145-12.0/145-16.0', '125-12.0/125-18.0/14

In [29]:
# ***************** 여기부터 *****************
reduction = np.reshape(output_array, (72, 3, -1))
print (output_array.shape, reduction.shape)

# 결과가 길어서 주석 처리 결과 확인하려면 주석 삭제 
for i in range(0, 72):
    for j in range(0, 3):
        #for k in range(0, 40):
            print(reduction[i][j])

(18, 4, 3, 40) (72, 3, 40)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
# ------------------------------------------------------------
# 결과 array data 화일 출력 - 1단계
# 72 X 3 = 216 Title (평가온도-평가전압) & data
# ------------------------------------------------------------

import  openpyxl  as  op  #openpyxl 모듈 import
import os

os.chdir("P:\자동데이타생성")

wb = op.Workbook()

ws = wb.create_sheet("Full_comb_of_three_cond",0) #wb 객체를 통해 새로운 시트 생성
ws = wb["Full_comb_of_three_cond"] #결과 출력용 Sheet로 설정하기

# title 출력
i=1

for x in range(0,216):
    ws.cell(row = 1, column = i).value = title_array[x]  # 1행(row=1)에 열을 바꾸면서 출력
    if x%3 == 2:
        i += 2  # 3열에 구분열 1열씩 추가 
    else:
        i += 1  # 열값 증가

i=2
j=1
for x in range(0,72):    
    for y in range(0,3): 
        for z in  range(0,40):
            ws.cell(row = i, column=j).value = reduction[x][y][z]  #A열(Column=1)에 행을 바꾸면서 출력
            i += 1  #행값 증가
        i = 2
        j += 1 # 열값 증가
    i = 2
    j += 1
 
wb.save("test_result3.xlsx") #해당 워크북(엑셀파일) 저장하기

In [ ]:
# ------------------------------------------------------------
# 
# 2. 미니탭 'Temp Volt Time censor' 형식 출력
# ------------------------------------------------------------

import  openpyxl  as  op  #openpyxl 모듈 import
import os

os.chdir("P:\자동데이타생성")

#path = r"P:\자동데이타생성"
#wb = op.load_workbook(path + "/test_result.xlsx")
wb = op.load_workbook("test_result.xlsx")

ws = wb.create_sheet("Minitab_data2",1) #wb 객체를 통해 새로운 시트 생성
ws = wb["Minitab_data2"] #결과 출력용 Sheet로 설정하기

# title 출력
 
for x in range(0,72):
    ws.cell(row = 1, column = x*5+1).value = 'Set '+str(x+1)+' : ' # 72 set 정보를 행(row=1)에 열을 바꾸면서 출력
    ws.cell(row = 1, column = x*5+2).value = title_array2[x]  
    ws.cell(row = 2, column = x*5+1).value = 'Temp'+str(x+1)
    ws.cell(row = 2, column = x*5+2).value = 'Vot'+str(x+1)
    ws.cell(row = 2, column = x*5+3).value = 'Time'+str(x+1)
    ws.cell(row = 2, column = x*5+4).value = 'Censor'+str(x+1)
 
title_array3 = np.reshape(title_array, (72, -1))

i=3
j=1
for x in range(0,72):    
    for y in range(0,3): 
        for z in  range(0,40):
            ws.cell(row = i, column=j).value = int(title_array3[x][y].split('-')[0])
            ws.cell(row = i, column=j+1).value = float(title_array3[x][y].split('-')[1])
            ws.cell(row = i, column=j+2).value = reduction[x][y][z]  #A열(Column=1)에 행을 바꾸면서 출력
            ws.cell(row = i, column=j+3).value = 0               # Censoring 판단 로직 필요
            i += 1  #행값 증가
    i = 3
    j += 5    
       
# i=3
# j=3
# for x in range(0,72):    
#     for y in range(0,3): 
#         for z in  range(0,40):
#             ws.cell(row = i, column=j).value = reduction[x][y][z]  #A열(Column=1)에 행을 바꾸면서 출력
#             i += 1  #행값 증가
#     i = 3
#     j += 5
 
wb.save("test_result0.xlsx") #해당 워크북(엑셀파일) 저장하기

In [ ]:
#openpyxl

import  openpyxl  as  op  #openpyxl 모듈 import

# 신규 파일로 객체를 생성하는 경우
wb = op.Workbook() #새로운 워크북 객체 생성

ws = wb.create_sheet("new_sheet1") #wb 객체를 통해 새로운 시트 생성(시트명 : new_sheet1)
print(ws) #ws 객체 출력해보기

ws = wb.active #활성화되어있는 시트 설정
print(ws)

ws = wb["new_sheet1"] #신규 Sheet로 설정하기
print(ws)

ws_list = wb.sheetnames  #해당 Workbook의 시트 목록을 리스트로 저장
print(ws_list) #리스트 출력

for  sht  in  ws_list:
    ws = wb[sht] #Sheet 객체 생성
    print(ws) #객체 출력

#기존에 만들어져 있는 파일로 객체를 생성하는 경우
#path = r"C:\Users\Desktop\VS CODE\Project\practice\연습"
#wb = op.load_workbook(path + "/test.xlsx")

# Excel에서 data 읽기
#import  openpyxl  as  op  #openpyxl 모듈 import

# wb = op.load_workbook(r"test.xlsx") #워크북 객체 생성(파일명 : test.xlsx)
# ws = wb.active  #활성화 되어있는 시트 설정(시트명 : "업")

# #방법 1 : Sheet의 Cell 속성 사용하기
# data1 = ws.cell(row=1, column=2).value

# #방법 2 : 엑셀 인덱스(Range) 사용하기
# data2 = ws["B1"].value

# #위 결과 출력해보기
# print("cell(1,2) : ", data1)
# print('Range("B1"):', data2)

#wb.save("test_result.xlsx") #해당 워크북(엑셀파일) 저장하기
#wb.save(r"C:\Users\Desktop\VS CODE\openpyxl_test.xlsx") #절대 경로 지정

#wb.save(r"C:\Users\Desktop\VS CODE\openpyxl_test.xlsx")
#wb.save("openpyxl_test.xlsx")

In [ ]:

import openpyxl as op   #openpyxl 모듈 import
import os

os.chdir("P:\자동데이타생성")

#import xlwings as xw
#bk1 = xw.Book('output_test.xlsx')
#sh1 = bk1.sheets(1)
#df1_des = bk1.sheets(1).range('B3:M13').options(pd.DataFrame, index=False, header=False).value

wb = op.load_workbook("test.xlsx") #워크북 객체 생성(파일명 : test.xlsx)
ws = wb.active  #활성화 되어있는 시트 설정(시트명 : "업")

datalist = [2,4,8,16,32,64,128,256] #임의의 숫자 리스트 정의

i=1  # 행값을 바꾸기 위한 인덱스 정의

for  data  in  datalist:
    ws.cell(row = i, column=1).value = data  #A열(Column=1)에 행을 바꾸면서 입력
    i=i+1  #행값 증가

wb.save("result.xlsx")


In [ ]:
df2_des = pd.DataFrame(df2.iloc[0:8, :4].dropna(axis = 0, how = 'all').values)
df2_des

In [ ]:
column = df2.iloc[8].dropna(axis = 0, how = 'all').to_list()
print(column)


In [ ]:
# tab name 취출
test_cond_list = [bk1.sheets(x).name for x in range(2,14)]
#test_cond_list.sort()

print(test_cond_list)

In [ ]:
df2_data = pd.DataFrame(df2.iloc[9:49, :4].dropna(axis = 0, how = 'all').values, columns = column)
df2_data

In [ ]:
column_cut = df2_data.loc[0:39, 'FAILURE HOUR'].values
print(column_cut)

In [ ]:
import numpy as np

max_data =40
i = len(test_temp)
j = len(test_volt)
k = max_data

new_array= np.zeros((i, j, k))
new_array[0][0] = column_cut

print(new_array)

In [ ]:
ar1[1][0][0]

In [ ]:
import sys

from PyQt5.QtCore import QAbstractTableModel, Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableView


class PandasModel(QAbstractTableModel):
    def __init__(self, data):
        super().__init__()
        self._data = data

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])

    def data(self, index, role=Qt.DisplayRole):
        if index.isValid():
            if role == Qt.DisplayRole or role == Qt.EditRole:
                value = self._data[index.row()][index.column()]
                return str(value)

    def setData(self, index, value, role):
        if role == Qt.EditRole:
            self._data[index.row()][index.column()] = value
            return True
        return False

    def flags(self, index):
        return Qt.ItemIsSelectable | Qt.ItemIsEnabled | Qt.ItemIsEditable


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.table = QTableView()

        data = [
            [1, 9, 2],
            [1, 0, -1],
            [3, 5, 2],
            [3, 3, 2],
            [5, 8, 9],
        ]

        self.model = PandasModel(data)
        self.table.setModel(self.model)

        self.setCentralWidget(self.table)


app = QApplication(sys.argv)
window = MainWindow()
window.show()
app.exec_()


In [ ]:
# https://hleecaster.com/excel-crawling-with-python/

import os
path = "./files"
file_list = os.listdir(path)
print(file_list)

from openpyxl import load_workbook

results = []
for file_name_raw in file_list:
    file_name = "./files/" + file_name_raw
    wb = load_workbook(filename=file_name, data_only=True)
    ws = wb.active
    result = []
    result.append(file_name_raw)
    result.append(ws['C2'].value)
    result.append(ws['C3'].value)
    result.append(ws['E2'].value)
    result.append(ws['E3'].value)
    results.append(result)
print(results)

from openpyxl import Workbook
wb = Workbook()
ws = wb.active

for i in results:
    ws.append(i)
wb.save("results.xlsx")

In [ ]:
i=1
           
for x in range(0,216):
    print(i)
    if x%3 == 2:
        i += 2  # 3열에 구분열 1열씩 추가 
    else:
        i += 1  # 열값 증가

In [2]:
from PyQt5.QtCore import *
import pandas as pd


class pandasModel(QAbstractTableModel):
    def __init__(self, df=pd.DataFrame()):
        super().__init__()
        self.df = df

    def rowCount(self, parent=None):
        return self.df.shape[0]

    def columnCount(self, index=None):
        return self.df.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid() or role != Qt.DisplayRole:
            return QVariant()
        return str(self.df.iloc[index.row(), index.column()])

    def flags(self, index):
        return Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsEditable

    def setData(self, index, value, role):
        if not index.isValid():
            return QVariant()
        if role == Qt.DisplayRole or role == Qt.EditRole:
            self.df.iloc[index.row(), index.column()] = value
            self.dataChanged.emit(index, index)
            return True
        return QVariant()

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if role != Qt.DisplayRole:
            return QVariant()

        if orientation == Qt.Horizontal:

            return self.df.columns[section]
        elif orientation == Qt.Vertical:
            return str(self.df.index[section])

In [1]:
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import os
import sys
import xlwings as xw
import pandas as pd

os.chdir("M:\DC-bias library_1771")
from main_wnd_intel import Ui_MainWindow

from PyQt5.QtCore import *
import pandas as pd


class pandasModel(QAbstractTableModel):
    def __init__(self, df=pd.DataFrame()):
        super().__init__()
        self.df = df

    def rowCount(self, parent=None):
        return self.df.shape[0]

    def columnCount(self, index=None):
        return self.df.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid() or role != Qt.DisplayRole:
            return QVariant()
        return str(self.df.iloc[index.row(), index.column()])

    def flags(self, index):
        return Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsEditable

    def setData(self, index, value, role):
        if not index.isValid():
            return QVariant()
        if role == Qt.DisplayRole or role == Qt.EditRole:
            self.df.iloc[index.row(), index.column()] = value
            self.dataChanged.emit(index, index)
            return True
        return QVariant()

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if role != Qt.DisplayRole:
            return QVariant()

        if orientation == Qt.Horizontal:

            return self.df.columns[section]
        elif orientation == Qt.Vertical:
            return str(self.df.index[section])
        
class Form(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.actionOpen_2.triggered.connect(self.open_file)
        
    def open_file(self):   
        os.chdir("P:\자동데이타생성")
        bk1 = xw.Book('03W225_AI44B5O.xlsx')
        df1_data = bk1.sheets(1).range('B14').options(pd.DataFrame, index=False, header=False, expand='table').value
        
        max_data = 40
        show_data = df1_data
        column = ['125-12.0', '125-14.0', '125-16.0', '125-18.0', '135-12.0', '135-14.0', '135-16.0', '135-18.0', '145-12.0', '145-14.0', '145-16.0', '145-18.0']
        show_data.columns = column
        new_index = range(1, max_data+1)
        show_data.index = new_index
        self.make_tableLib(show_data)
        
        test_temp = ['125', '135', '145']
        test_volt = ['12.0', '14.0', '16.0', '18.0']
        testcond = pd.DataFrame(columns = test_volt, index = test_temp)
        show_cond = testcond.fillna('V')
        self.make_tableConst(show_cond)

    def make_tableLib(self, df):
        model = pandasModel(df)
        self.tableLib.setModel(model)
        self.tableLib.resizeColumnsToContents()
        self.tableLib.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableLib.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
    
    def make_tableConst(self, df):
        model = pandasModel(df)
        self.tableConst.setModel(model)
        self.tableConst.resizeColumnsToContents()
        self.tableConst.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableConst.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
app = QApplication(sys.argv)
w = Form()
w.show()

app.exec_()

0