In [66]:
# [파이썬/업무자동화] 엑셀 전체 셀 내용 중 특정 문자만 변경/제거하기
# https://ybworld.tistory.com/112

import openpyxl as op
import numpy as np

#path는 대상이 되는 엑셀파일의 절대 경로
def corretion(path : str):
    #openpyxl 워크북 정의
    wb = op.load_workbook(path)
    #워크북의 활성화된 시트를 객체로 정의
    ws = wb.active

    #해당 시트의 마지막 열, 마지막 행 
    column_max = ws.max_column
    row_max = ws.max_row
    no_of_comb = int(input("Set 수는? : "))
    print(column_max, row_max, "\n")

    temp = np.zeros((no_of_comb, 6))
    volt = np.zeros((no_of_comb, 6))
    life = np.zeros((no_of_comb, 4))
    
    #열마다 행을 for loop문 진행
    for col_num in range(1, column_max+1):
        for row_num in range(1, row_max+1):
            for x in range(0, no_of_comb):
                #tempstr : cell값이 문자열이 아닌 경우를 감안하여 str로 바꿔줌
                tempstr = str(ws.cell(row = row_num, column = col_num).value)
                tempstr2 = str(ws.cell(row = row_num+1, column = col_num).value)
#                 if (tempstr == 'Temp'+str(x+1) and tempstr2 == 'Vot'+str(x+1)):
#                     print (col_num, row_num, tempstr, tempstr2)
                       
                if tempstr == 'Temp'+str(x+1):
                    if tempstr2 == 'Vot'+str(x+1):
                        for y in range(0, 6):
                            temp[x][y] = ws.cell(row = row_num, column = col_num+y+1).value
                            volt[x][y] = ws.cell(row = row_num+1, column = col_num+y+1).value
                    elif tempstr2 == '0.001':   
                        for y in range(0, 4):
                            life[x][y] = ws.cell(row = row_num+1, column = col_num+y+3).value
               
             
                    
                                
    print("\n")                                              
    print(temp, "\n", volt, "\n", life)

    print("==============================    Extraction Result   =============================") 
    print(" Set No              Temp Accel_Low             Volt Accel_Low             Life_Low")
    for i in range(0, no_of_comb):
        print('Set'+str(i+1), temp[i][4], abs(volt[i][5]), life[i][2]/8750)
        
        
        
#             #문자열 함수 replace 사용(,를 빈칸으로)
#             data = tempstr.replace(",","")
#             #빈 셀의 경우 None이라는 문자열 타입이므로 제외하고 데이터 입력
#             if data != "None":
#                 ws.cell(row = row_num, column = col_num).value = data   
                     
            #원하는 문자열이면 이후 필요한 cell 내용 추출
            
            

    #저장
#     wb.save("correction_result.xlsx")

if __name__ == "__main__":
#     path = input("화일경로는 ? \n Ex) r'P:\자동데이타생성\쎄션 데이터 추출.xlsx' : ")
    path = r"P:\자동데이타생성\쎄션 데이터 추출.xlsx"

    #함수 실행
    corretion(path)

Set 수는? : 72
10 3387 



[[1.47246e+00 8.74927e-02 1.68300e+01 0.00000e+00 1.32855e+00 1.61638e+00]
 [1.57199e+00 8.84924e-02 1.77600e+01 0.00000e+00 1.42643e+00 1.71755e+00]
 [1.47246e+00 9.49367e-02 1.55100e+01 0.00000e+00 1.31631e+00 1.62862e+00]
 [1.57199e+00 7.43134e-02 2.11500e+01 0.00000e+00 1.44975e+00 1.69422e+00]
 [1.47246e+00 9.32908e-02 1.57800e+01 0.00000e+00 1.31902e+00 1.62591e+00]
 [1.49161e+00 1.01745e-01 1.46600e+01 0.00000e+00 1.32425e+00 1.65896e+00]
 [1.47246e+00 1.02401e-01 1.43800e+01 0.00000e+00 1.30403e+00 1.64090e+00]
 [1.49161e+00 8.96862e-02 1.66300e+01 0.00000e+00 1.34409e+00 1.63913e+00]
 [1.47246e+00 1.11894e-01 1.31600e+01 0.00000e+00 1.28842e+00 1.65651e+00]
 [1.28117e+00 1.10973e-01 1.15400e+01 0.00000e+00 1.09864e+00 1.46371e+00]
 [1.47246e+00 9.29072e-02 1.58500e+01 0.00000e+00 1.31965e+00 1.62528e+00]
 [1.28117e+00 1.00033e-01 1.28100e+01 0.00000e+00 1.11663e+00 1.44571e+00]
 [1.57199e+00 7.34073e-02 2.14100e+01 0.00000e+00 1.45125e+00 1.69273e+00]


In [79]:
import random
import openpyxl as op

#가상 엑셀파일을 생성할 주소
path = r"M:\Test"
#몇개 생성할것 인가?
n = 10

#random 모듈 및 openpyxl 통한 가상의 엑셀파일 및 랜덤 데이터 생성
for i in range(1, n+1):

#     wb = op.Workbook()
#     ws = wb.active
#     #random모듈의 randrage 함수를 통한 랜덤 숫자 data 생성 및 엑셀입력
#     for row_num in range(1,11):
#         ws.cell(row=row_num, column=1).value = str(row_num)+"번째 data"
#         ws.cell(row=row_num, column=2).value = random.randrange(1,100)
    
#     #엑셀 파일 저장
#     wb.save(path+"\"+str(i)+".xlsx")
    print(path+"\")   

SyntaxError: EOL while scanning string literal (<ipython-input-79-6e490bcc89af>, line 21)

In [ ]:
import openpyxl as op
import os


#셀주소를 직접 입력받아 저장하는 함수
def saveCellAddress()->list:
    
    num = int(input('몇개 입력받을거야? : '))
    #엑셀 셀 주소를 저장하기 위한 빈 리스트 생성
    save_cell = []
    #입력받을 숫자만큼 데이터를 받고 for문 실행
    for i in range(1,num+1):
        print(str(i)+"번째 입력 : ")
        cell = str(input('첫번째 셀 주소 입력 ex)A1,B1: '))
        save_cell.append(cell)
    print(save_cell)
    
    return save_cell

#엑셀 파일 있는 주소, Cell 주소 입력받아 정해진 위치 값들 딕셔너리로 저장
def saveData(path : str, cell_list : list):
    excellist = os.listdir(path) #설정한 폴더경로에 있는 엑셀파일명을 리스트화
    dic = {} #빈 딕셔너리 생성
    
    #cell 주소당 빈 딕셔너리 생성
    for cell in cell_list:
        dic[cell] = ''

    #설정한 cell 주소에 대해 모든 엑셀파일을 루프로 돌면서 데이터를 저장. 
    for cell in cell_list:
        templist = [] # 빈 임시 리스트 생성
        for file in excellist: #엑셀파일 list를 루프로 실행
            wb = op.load_workbook(path + "/" + file)
            ws = wb.active
            templist.append(ws[cell].value) #빈 임시 리스트에 필요한 값을 가져옴.
        dic[cell] = templist #임시 리스트를 딕셔너리화(key : cell주소, value : 값 리스트)
    print(dic)
   
    return dic

#딕셔너리를 매개변수로 입력받아 새로운 엑셀파일에 취합하는 함수
def writeExcel(dic):
    #새로운 엑셀파일 생성
    wb = op.Workbook()
    ws = wb.active
    
    #엑셀파일 입력을 위한 reference 
    row_num=1 #행
    col_num=1 #열

    #딕셔너리 key값을 활용하여 for문 진행
    for key in dic.keys():
        #각 key값에 따른 리스트를 다시 for문 진행
        for data in dic[key]:            
            ws.cell(row=row_num, column = col_num).value = data # 입력
            row_num = row_num + 1 #행값 증가
        col_num = col_num+1 #열값 증가
        row_num = 1 #각 cell주소에 대한 data 입력이 끝나면 행=1로 초기화
    
    #저장
    wb.save("dic_Result.xlsx")
    print("생성 완료")

if __name__ == "__main__":

    path = r"C:\Users\Yongbeom Jeong\Desktop\VS CODE\Project\collect_Data\random"
    cell = saveCellAddress()
    dic = saveData(path, cell)
    writeExcel(dic)
        

